---version: 0, author: DlSync
create or replace TAG ${EXAMPLE_DB}.${MAIN_SCHEMA}.COLUMN_CLASSIFICATION allowed_values 'PUBLIC', 'INTERNAL', 'RESTRICTED', 'SENSITIVE';
---rollback: DROP TAG IF EXISTS ${EXAMPLE_DB}.${MAIN_SCHEMA}.COLUMN_CLASSIFICATION;
---verify: SHOW TAGS LIKE 'COLUMN_CLASSIFICATION' IN ${EXAMPLE_DB}.${MAIN_SCHEMA};