CREATE OR REPLACE CORTEX SEARCH SERVICE ${EXAMPLE_DB}.${MAIN_SCHEMA}.PRODUCT_SEARCH
  ON PRODUCT_NAME
  ATTRIBUTES PRICE, STOCK
  WAREHOUSE = ${MY_WAREHOUSE}
  TARGET_LAG = '1 hour'
AS (
  SELECT
    PRODUCT_NAME,
    PRICE,
    STOCK
  FROM ${EXAMPLE_DB}.${MAIN_SCHEMA}.PRODUCTS
);
